CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_STATUS_LED=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000
CONFIG_ZMK_NON_LIPO_MIN_MV=1000
CONFIG_ZMK_NON_LIPO_LOW_MV=900

CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
# スクロール専用モードを完全に解除（1本指カーソル・2本指スクロールを有効化）
CONFIG_IQS7211E_SCROLLER_MODE=n

# 仕様書通りの慣性スクロール設定（お好みで追加してください）
CONFIG_IQS7211E_SCROLLER_INERTIA=y
CONFIG_IQS7211E_SCROLLER_INERTIA_DECAY_PERMILLE=920
CONFIG_IQS7211E_SCROLLER_INERTIA_STOP_THRESHOLD_Q8=96
